---
run:
  timeout: 10m
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godot
    - revive
    - gofmt
