---
run:
  timeout: 10m
linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godot
    - revive
    - gofmt
