---
defaults:
  params:
    - name: sonar-enabled
      value: "true"
    - name: whitesource-product-name
      value: platform
    - name: whitesource-project-name
      value: tekton-toolbox
    - name: go-version
      value: "1.19"
    - name: go-lint-version
      value: "1.50.1"
triggers:
  - name: pr
    pipelines:
      - name: yaml-sanity
        metadata:
        pipelineRef:
          name: yaml-sanity
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/yaml:0.1
      - name: go-sanity
        pipelineRef:
          name: go-sanity
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/go:0.3
      - name: buildkit-gcs-log-proxy
        metadata:
          annotations:
            tekton.ec.ai/memberOf: gcs-log-proxy
        pipelineRef:
          name: buildkit
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/buildkit:0.1
        params:
          - name: name
            value: gcs-log-proxy
          - name: dockerfile
            value: cmd/gcs-log-proxy/Dockerfile
          - name: image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/dev/tekton-toolbox/gcs-log-proxy
          - name: tag
            value: body.pull_request.head.sha
          - name: cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/gcs-log-proxy
          - name: cache-tag
            value: body.pull_request.number
      - name: buildkit-github-pipeline-config
        metadata:
          annotations:
            tekton.ec.ai/memberOf: github-pipeline-config
        pipelineRef:
          name: buildkit
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/buildkit:0.1
        params:
          - name: name
            value: github-pipeline-config
          - name: dockerfile
            value: cmd/github-pipeline-config/Dockerfile
          - name: image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/dev/tekton-toolbox/github-pipeline-config
          - name: tag
            value: body.pull_request.head.sha
          - name: cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/github-pipeline-config
          - name: cache-tag
            value: body.pull_request.number
      - name: buildkit-github-status-sync
        metadata:
          annotations:
            tekton.ec.ai/memberOf: github-status-sync
        pipelineRef:
          name: buildkit
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/buildkit:0.1
        params:
          - name: name
            value: github-status-sync
          - name: dockerfile
            value: cmd/github-status-sync/Dockerfile
          - name: image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/dev/tekton-toolbox/github-status-sync
          - name: tag
            value: body.pull_request.head.sha
          - name: cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/github-status-sync
          - name: cache-tag
            value: body.pull_request.number
      - name: buildkit-kube-pipeline-config
        metadata:
          annotations:
            tekton.ec.ai/memberOf: kube-pipeline-config
        pipelineRef:
          name: buildkit
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/buildkit:0.1
        params:
          - name: name
            value: kube-pipeline-config
          - name: dockerfile
            value: cmd/kube-pipeline-config/Dockerfile
          - name: image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/dev/tekton-toolbox/kube-pipeline-config
          - name: tag
            value: body.pull_request.head.sha
          - name: cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/kube-pipeline-config
          - name: cache-tag
            value: body.pull_request.number
      - name: buildkit-pipeline-config-trigger
        metadata:
          annotations:
            tekton.ec.ai/memberOf: pipeline-config-trigger
        pipelineRef:
          name: buildkit
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/buildkit:0.1
        params:
          - name: name
            value: pipeline-config-trigger
          - name: dockerfile
            value: cmd/pipeline-config-trigger/Dockerfile
          - name: image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/dev/tekton-toolbox/pipeline-config-trigger
          - name: tag
            value: body.pull_request.head.sha
          - name: cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/pipeline-config-trigger
          - name: cache-tag
            value: body.pull_request.number
      - name: whitesource
        pipelineRef:
          name: whitesource
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/whitesource:0.1
        params:
          - name: buildkit-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/whitesource/platform/tekton-toolbox
          - name: buildkit-tag
            value: body.pull_request.head.sha
          - name: buildkit-cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/whitesource/platform/tekton-toolbox
          - name: buildkit-cache-tag
            value: latest
  - name: main
    pipelines:
      - name: go-sanity
        pipelineRef:
          name: go-sanity
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/go:0.3
      - name: gitops-gcs-log-proxy
        metadata:
          annotations:
            tekton.ec.ai/memberOf: gcs-log-proxy
        pipelineRef:
          name: gitops-release
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/gitops:0.2
        params:
          - name: argocd-name
            value: tekton-toolbox
          - name: gitops-name
            value: gcs-log-proxy
          - name: gitops-context
            value: platform/tekton-toolbox/gcs-log-proxy
          - name: gitops-overlays
            value: |
              src
          - name: gitops-script
            value: |
              kustomize edit set image "us-east4-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/gcs-log-proxy=$BUILDKIT_IMAGE"
          - name: buildkit-name
            value: tekton-pipeline-config
          - name: buildkit-dockerfile
            value: cmd/gcs-log-proxy/Dockerfile
          - name: buildkit-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/gcs-log-proxy
          - name: buildkit-tag
            value: body.head_commit.id
          - name: buildkit-cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/gcs-log-proxy
          - name: buildkit-cache-tag
            value: latest
      - name: gitops-github-pipeline-config
        metadata:
          annotations:
            tekton.ec.ai/memberOf: github-pipeline-config
        pipelineRef:
          name: gitops-release
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/gitops:0.2
        params:
          - name: argocd-name
            value: tekton-toolbox
          - name: gitops-name
            value: github-pipeline-config
          - name: gitops-context
            value: platform/tekton-toolbox/github-pipeline-config
          - name: gitops-overlays
            value: |
              src
          - name: gitops-script
            value: |
              kustomize edit set image "us-east4-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/github-pipeline-config=$BUILDKIT_IMAGE"
          - name: buildkit-name
            value: tekton-pipeline-config
          - name: buildkit-dockerfile
            value: cmd/github-pipeline-config/Dockerfile
          - name: buildkit-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/github-pipeline-config
          - name: buildkit-tag
            value: body.head_commit.id
          - name: buildkit-cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/github-pipeline-config
          - name: buildkit-cache-tag
            value: latest
      - name: gitops-github-status-sync
        metadata:
          annotations:
            tekton.ec.ai/memberOf: github-status-sync
        pipelineRef:
          name: gitops-release
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/gitops:0.2
        params:
          - name: argocd-name
            value: tekton-toolbox
          - name: gitops-name
            value: github-status-sync
          - name: gitops-context
            value: platform/tekton-toolbox/github-status-sync
          - name: gitops-overlays
            value: |
              src
          - name: gitops-script
            value: |
              kustomize edit set image "us-east4-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/github-status-sync=$BUILDKIT_IMAGE"
          - name: buildkit-name
            value: tekton-pipeline-config
          - name: buildkit-dockerfile
            value: cmd/github-status-sync/Dockerfile
          - name: buildkit-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/github-status-sync
          - name: buildkit-tag
            value: body.head_commit.id
          - name: buildkit-cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/github-status-sync
          - name: buildkit-cache-tag
            value: latest
      - name: gitops-kube-pipeline-config
        metadata:
          annotations:
            tekton.ec.ai/memberOf: kube-pipeline-config
        pipelineRef:
          name: gitops-release
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/gitops:0.2
        params:
          - name: argocd-name
            value: tekton-toolbox
          - name: gitops-name
            value: kube-pipeline-config
          - name: gitops-context
            value: platform/tekton-toolbox/kube-pipeline-config
          - name: gitops-overlays
            value: |
              src
          - name: gitops-script
            value: |
              kustomize edit set image "us-east4-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/kube-pipeline-config=$BUILDKIT_IMAGE"
          - name: buildkit-name
            value: tekton-pipeline-config
          - name: buildkit-dockerfile
            value: cmd/kube-pipeline-config/Dockerfile
          - name: buildkit-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/kube-pipeline-config
          - name: buildkit-tag
            value: body.head_commit.id
          - name: buildkit-cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/kube-pipeline-config
          - name: buildkit-cache-tag
            value: latest
      - name: gitops-pipeline-config-trigger
        metadata:
          annotations:
            tekton.ec.ai/memberOf: pipeline-config-trigger
        pipelineRef:
          name: gitops-release
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/gitops:0.2
        params:
          - name: argocd-name
            value: tekton-toolbox
          - name: gitops-name
            value: pipeline-config-trigger
          - name: gitops-context
            value: platform/tekton-toolbox/pipeline-config-trigger
          - name: gitops-overlays
            value: |
              src
          - name: gitops-script
            value: |
              kustomize edit set image "us-east4-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/pipeline-config-trigger=$BUILDKIT_IMAGE"
          - name: buildkit-name
            value: tekton-pipeline-config
          - name: buildkit-dockerfile
            value: cmd/pipeline-config-trigger/Dockerfile
          - name: buildkit-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/pipeline-config-trigger
          - name: buildkit-tag
            value: body.head_commit.id
          - name: buildkit-cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/pipeline-config-trigger
          - name: buildkit-cache-tag
            value: latest
      - name: whitesource
        pipelineRef:
          name: whitesource
          bundle: us-east4-docker.pkg.dev/elementalcognition-app-source/tekton-catalog/pipeline/whitesource:0.1
        params:
          - name: buildkit-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/whitesource/platform/tekton-toolbox
          - name: buildkit-tag
            value: body.head_commit.id
          - name: buildkit-cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/whitesource/platform/tekton-toolbox
          - name: buildkit-cache-tag
            value: latest
