---
defaults:
  params:
    - name: sonar-enabled
      value: "true"
    - name: whitesource-product-name
      value: platform
    - name: whitesource-project-name
      value: tekton-toolbox
    - name: go-version
      value: "1.19"
    - name: go-lint-version
      value: "1.50.1"
triggers:
  - name: pr
    pipelines:
      - name: go-sanity
        pipelineRef:
          resolver: git
          params:
            - name: repo
              value: tekton-catalog-new
            - name: revision
              value: main
            - name: pathInRepo
              value: pipeline/go/0.3/go-sanity.yaml
      - name: gitops-gcs-log-proxy
        metadata:
          annotations:
            tekton.ec.ai/memberOf: gcs-log-proxy
        pipelineRef:
          resolver: git
          params:
            - name: repo
              value: tekton-catalog-new
            - name: revision
              value: main
            - name: pathInRepo
              value: pipeline/gitops/0.3/gitops-release.yaml
        params:
          - name: argocd-name
            value: tekton-toolbox
          - name: gitops-name
            value: gcs-log-proxy
          - name: gitops-context
            value: platform/tekton-toolbox/gcs-log-proxy
          - name: gitops-overlays
            value: |
              src
          - name: gitops-script
            value: |
              kustomize edit set image "us-central1-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/gcs-log-proxy=$BUILDKIT_IMAGE"
          - name: buildkit-name
            value: tekton-pipeline-config
          - name: buildkit-dockerfile
            value: cmd/gcs-log-proxy/Dockerfile
          - name: buildkit-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/platform/tekton-toolbox/gcs-log-proxy
          - name: buildkit-tag
            value: body.pull_request.head.sha
          - name: buildkit-cache-image
            value: us-central1-docker.pkg.dev/elementalcognition-app-source/tekton-cache/buildkit/platform/tekton-toolbox/gcs-log-proxy
          - name: buildkit-cache-tag
            value: latest
